{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flowgate.fullname" . }}-postgres-pvc
  labels:
    {{- include "flowgate.labels" . | nindent 4 }}
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowgate.fullname" . }}-postgres
  labels:
    {{- include "flowgate.labels" . | nindent 4 }}
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "flowgate.selectorLabels" . | nindent 6 }}
      component: postgres
  template:
    metadata:
      labels:
        {{- include "flowgate.selectorLabels" . | nindent 8 }}
        component: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.auth.postgresUser | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.auth.postgresPassword | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.auth.postgresDatabase | quote }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "flowgate.fullname" . }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgate.fullname" . }}-postgres
  labels:
    {{- include "flowgate.labels" . | nindent 4 }}
    component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "flowgate.selectorLabels" . | nindent 4 }}
    component: postgres
{{- end }}


