apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowgate.fullname" . }}-secrets
  labels:
    {{- include "flowgate.labels" . | nindent 4 }}
type: Opaque
data:
  secretKey: {{ .Values.secrets.secretKey | b64enc | quote }}
  databasePassword: {{ .Values.secrets.databasePassword | b64enc | quote }}


