apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgate.fullname" . }}-opamp
  labels:
    {{- include "flowgate.labels" . | nindent 4 }}
    component: opamp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.opamp.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flowgate.selectorLabels" . | nindent 4 }}
    component: opamp


