apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgate.fullname" . }}-frontend
  labels:
    {{- include "flowgate.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flowgate.selectorLabels" . | nindent 4 }}
    component: frontend


